name: Golint

on:
  push:
    branches:
      - main
    paths:
      - '**.go'
      - '.github/workflows/golangci-lint.yml'
  pull_request:
    paths:
      - '**.go'
      - '.github/workflows/golangci-lint.yml'

jobs:
  golangci:
    name: Format
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go_version: ['1.16', '1.17', '1.18']
    steps:
      - id: setup
        name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go_version }}

      - id: checkout
        name: Checkout PR
        uses: actions/checkout@v2

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.40
