name: Gotest

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ['1.16', '1.17', '1.18']
    steps:
      - id: setup
        name: Setup Golang
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
          stable: ${{ !contains(matrix.go, 'beta') }}

      - id: checkout
        name: Checkout PR
        uses: actions/checkout@v2

      - id: gcloud
        name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2

      - id: install
        name: Install Deps
        run: go get ./...

      - id: gotest
        name: Run Go test
        run: make test
        env:
          GITHUB_CI: true

      - id: covecov
        name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          files: ./coverage.txt,./aws/coverage.txt,./jsonschema/coverage.txt,./protobuf/coverage.txt
